import Hero from "@/components/home-page/hero";
import FeaturedPosts from "@/components/home-page/featured-posts";
export default function Home() {
  const DUMMY_POSTS = [
    {
      slug: "getting-started-with-nextjs",
      title: "Getting Started with NextJS",
      image: "getting-started-nextjs.png",
      excerpt:
        "NextJS is the React framework for production - it makes building fullstack React apps and sites a breeze and ships with built-in SSR.",
      date: "2022-02-10",
    },
    {
      slug: "getting-started-with-nextjs2",
      title: "Getting Started with NextJS",
      image: "getting-started-nextjs.png",
      excerpt:
        "NextJS is the React framework for production - it makes building fullstack React apps and sites a breeze and ships with built-in SSR.",
      date: "2022-02-10",
    },
    {
      slug: "getting-started-with-nextjs3",
      title: "Getting Started with NextJS",
      image: "getting-started-nextjs.png",
      excerpt:
        "NextJS is the React framework for production - it makes building fullstack React apps and sites a breeze and ships with built-in SSR.",
      date: "2022-02-10",
    },
    {
      slug: "getting-started-with-nextjs4",
      title: "Getting Started with NextJS",
      image: "getting-started-nextjs.png",
      excerpt:
        "NextJS is the React framework for production - it makes building fullstack React apps and sites a breeze and ships with built-in SSR.",
      date: "2022-02-10",
    },
  ];

  return (
    <>
      <Hero />
      <FeaturedPosts posts={DUMMY_POSTS} />
    </>
  );
}

//installed:

//npm install react-markdown  - converts markdown to JSX
//npm install gray-matter - allows us to read a markdown file and split it into metadata and the actual markdown content.

//To render:

//1) Hero => Present ourselves
//2) Featured Posts

// import Head from "next/head";
// <Head>
// <title>Create Next App</title>
// <meta name="description" content="Generated by create next app" />
// <meta name="viewport" content="width=device-width, initial-scale=1" />
// <link rel="icon" href="/favicon.ico" />
// </Head>
