import Head from "next/head";
import Hero from "@/components/home-page/hero";
import FeaturedPosts from "@/components/home-page/featured-posts";
import { getFeaturedPosts } from "../../lib/posts-util";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Max&apos;s Blog</title>
        <meta
          name="description"
          content="I post about programming and web develpment."
        />
      </Head>
      <Hero />
      <FeaturedPosts posts={props.posts} />
    </>
  );
}

export function getStaticProps() {
  const featuredPosts = getFeaturedPosts();

  return {
    props: {
      posts: featuredPosts,
    },
  };
}

//installed:

//npm install react-markdown  - converts markdown to JSX
//npm install gray-matter - allows us to read a markdown file and split it into metadata and the actual markdown content.
//npm install react-syntax-highlighter  - this package makes highlighting code in a pleasant way simple - for displaying the code snippets

//To render:

//1) Hero => Present ourselves
//2) Featured Posts

//To add metadat:

// import Head from "next/head";
// <Head>
// <title>Create Next App</title>
// <meta name="description" content="Generated by create next app" />
// <meta name="viewport" content="width=device-width, initial-scale=1" />
// <link rel="icon" href="/favicon.ico" />
// </Head>
